# Generated by Django 4.0.4 on 2022-04-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_myfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
