# Generated by Django 4.0.4 on 2022-04-28 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_questions_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10000)),
                ('optiion1', models.CharField(max_length=3000)),
                ('optiion2', models.CharField(max_length=3000)),
                ('optiion3', models.CharField(max_length=3000)),
                ('optiion4', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='QuizTaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='MyFile',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='type',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Teacher',
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.question')),
                ('Answer', models.CharField(max_length=3000)),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exam'),
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question', to='api.exam'),
        ),
        migrations.AddField(
            model_name='assign',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.exam'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.subject'),
        ),
    ]
