# Generated by Django 4.0.4 on 2022-04-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_assign_question_quiztaker_subject_delete_myfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='optiion1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='optiion2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='optiion3',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='optiion4',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=20),
        ),
    ]
